import type { Node, Edge } from "reactflow"
import type { Template } from "@/components/template-panel"

const defaultDisplaySettings = {
  showHostname: true,
  showIpAddress: true,
  showOs: true,
  showServices: true,
  showCriticality: true,
  showActions: true,
  showDescription: true,
  showUsername: false,
  showDomain: false,
  showAccountType: false,
  showAccountSource: false,
  showAccountStatus: false,
  showRiskLevel: false,
  showMfaStatus: false,
  showPrivileges: false,
  showGroups: false,
  showMethod: false,
  showDestination: false,
  showProtocol: false,
  showStatus: false,
  showVolume: false,
  showDataTypes: false,
  showC2Type: false,
  showC2Server: false,
  showC2Protocol: false,
  showBeaconInterval: false,
  showImplantType: false,
  showTenantId: true,
  showTenantName: true,
  showCloudProvider: true,
  showTenantType: true,
  showRegion: false,
  showEnvironment: false,
  showResourceCount: false,
  showSecurityScore: false,
  showCompromised: false,
  showInvestigationStatus: false,
  showTargetIndustries: true,
  showIp: true,
  showAttackVectors: true,
  showInfrastructureAge: false,
  showLastSeen: false,
  showFirstSeen: false,
  showInfrastructureStatus: true,
  showThreatActor: true,
  showLocation: false,
  showHostingProvider: false,
  showInfrastructureType: false,
}

export const builtInTemplates: Template[] = [
  // Basic Web Application Attack (existing)
  {
    id: "simple-web-attack",
    name: "Basic Web Application Attack",
    description: "Simple web application compromise through SQL injection leading to database access",
    category: "Web Security",
    tags: ["web", "sql-injection", "database", "beginner"],
    createdAt: "2024-01-01T00:00:00Z",
    isBuiltIn: true,
    incidentLog: [
      {
        id: "incident-simple-web-attack-1",
        timestamp: "2024-01-15T08:15:00Z",
        description: "Initial triage completed; scoped affected assets and logged findings.",
        category: "Observation",
      },
    ],
    nodes: [
      {
        id: "web-server-1",
        type: "customNode",
        position: { x: 100, y: 100 },
        data: {
          label: "Web Application",
          type: "web-server",
          hostname: "webapp.company.com",
          ipAddress: "203.0.113.10",
          os: "Ubuntu 20.04",
          criticality: "Medium",
          services: ["HTTP", "HTTPS", "MySQL"],
          actions: [
            {
              id: "action-1",
              type: "Initial Access",
              technique: "SQL Injection",
              details: "Exploited login form with SQL injection to bypass authentication",
            },
          ],
          description: "Public-facing web application with vulnerable login form",
          displaySettings: { ...defaultDisplaySettings },
          isCompromised: true,
    investigationStatus: "No Status",
        },
      },
      {
        id: "database-1",
        type: "customNode",
        position: { x: 400, y: 100 },
        data: {
          label: "Database Server",
          type: "database",
          hostname: "db-prod-01",
          ipAddress: "10.0.1.50",
          os: "MySQL 8.0",
          criticality: "High",
          services: ["MySQL", "SSH"],
          actions: [
            {
              id: "action-2",
              type: "Collection",
              technique: "Data from Information Repositories",
              details: "Extracted customer data and user credentials from database",
            },
          ],
          description: "Backend database containing customer information",
          displaySettings: { ...defaultDisplaySettings },
          isCompromised: true,
    investigationStatus: "No Status",
        },
      },
    ],
    edges: [
      {
        id: "e-web-db",
        source: "web-server-1",
        target: "database-1",
        type: "customEdge",
        data: {
          label: "Database Access",
          actionType: "Lateral Movement",
          toolUsed: "SQL Injection",
          userUsed: "www-data",
          timestamp: "2024-01-15T10:30:00Z",
          mitreAttackId: "T1190",
          description: "Used SQL injection to access backend database",
        },
      },
    ],
  },
  
  // Advanced Ransomware Attack
  {
    id: "advanced-ransomware",
    name: "Advanced Ransomware Attack",
    description: "Sophisticated ransomware attack with lateral movement and data exfiltration",
    category: "Malware",
    tags: ["ransomware", "lateral-movement", "exfiltration", "privilege-escalation", "advanced", "cloud"],
    createdAt: "2024-01-01T00:00:00Z",
    isBuiltIn: true,
    incidentLog: [
      {
        id: "incident-advanced-ransomware-1",
        timestamp: "2024-01-15T08:15:00Z",
        description: "Initial triage completed; scoped affected assets and logged findings.",
        category: "Observation",
      },
    ],
    nodes: [
      {
        id: "attacker-1",
        type: "customNode",
        position: { x: 50, y: 200 },
        data: {
          label: "Attacker Infrastructure",
          type: "attacker",
          criticality: "Critical",
          services: ["C2 Server", "Exfiltration Server"],
          actions: [
            {
              id: "action-1",
              type: "Initial Access",
              technique: "Phishing with Malware",
              details: "Deployed ransomware via spear-phishing campaign",
            },
          ],
          description: "External attacker infrastructure",
          displaySettings: { ...defaultDisplaySettings },
          attackerData: {
            targetIndustries: ["Financial Services", "Healthcare"],
            ip: "192.168.1.100",
            attackVectors: ["Phishing", "Ransomware", "APT"],
            infrastructureAge: "2 years",
            lastSeen: "2024-01-15T10:30:00Z",
            firstSeen: "2022-01-01T00:00:00Z",
            infrastructureStatus: "Active",
            threatActor: "APT29",
            location: "Russia",
            hostingProvider: "OVH",
            infrastructureType: "VPS",
          },
          isCompromised: false,
    investigationStatus: "No Status",
        },
      },
      {
        id: "workstation-1",
        type: "customNode",
        position: { x: 300, y: 100 },
        data: {
          label: "User Workstation",
          type: "workstation",
          hostname: "WS-FINANCE-01",
          ipAddress: "10.0.2.15",
          os: "Windows 11 Pro",
          criticality: "Medium",
          services: ["RDP", "SMB", "HTTP"],
          actions: [
            {
              id: "action-2",
              type: "Initial Access",
              technique: "User Execution",
              details: "User executed malicious attachment from phishing email",
            },
          ],
          description: "Finance department workstation",
          displaySettings: { ...defaultDisplaySettings },
          isCompromised: true,
    investigationStatus: "No Status",
        },
      },
      {
        id: "file-server-1",
        type: "customNode",
        position: { x: 550, y: 100 },
        data: {
          label: "File Server",
          type: "file-server",
          hostname: "FS-PROD-01",
          ipAddress: "10.0.1.20",
          os: "Windows Server 2019",
          criticality: "High",
          services: ["SMB", "RDP", "AD"],
          actions: [
            {
              id: "action-3",
              type: "Lateral Movement",
              technique: "Remote Services",
              details: "Accessed via stolen credentials and SMB",
            },
          ],
          description: "Primary file server with business data",
          displaySettings: { ...defaultDisplaySettings },
          isCompromised: true,
    investigationStatus: "No Status",
        },
      },
      {
        id: "domain-controller-1",
        type: "customNode",
        position: { x: 800, y: 100 },
        data: {
          label: "Domain Controller",
          type: "domain-controller",
          hostname: "DC-PRIMARY",
          ipAddress: "10.0.1.10",
          os: "Windows Server 2019",
          criticality: "Critical",
          services: ["AD DS", "DNS", "LDAP"],
          actions: [
            {
              id: "action-4",
              type: "Privilege Escalation",
              technique: "Domain Admin Access",
              details: "Obtained domain admin privileges via credential theft",
            },
          ],
          description: "Primary domain controller",
          displaySettings: { ...defaultDisplaySettings },
          isCompromised: true,
    investigationStatus: "No Status",
        },
      },
              {
          id: "cloud-storage-1",
          type: "customNode",
          position: { x: 550, y: 300 },
          data: {
            label: "Cloud Storage",
            type: "cloud-storage",
            hostname: "attacker-bucket",
            ipAddress: "s3.amazonaws.com",
            os: "AWS S3",
            criticality: "Critical",
            services: ["S3", "HTTPS"],
            actions: [
              {
                id: "action-5",
                type: "Exfiltration",
                technique: "Data Transfer Size Limits",
                details: "Exfiltrated 500GB of sensitive data before encryption",
              },
            ],
            description: "Attacker-controlled cloud storage for data exfiltration",
            displaySettings: { ...defaultDisplaySettings },
            isCompromised: true,
    investigationStatus: "No Status",
          },
        },
    ],
    edges: [
      {
        id: "e-attacker-workstation",
        source: "attacker-1",
        target: "workstation-1",
        type: "customEdge",
        data: {
          label: "Phishing Delivery",
          actionType: "Initial Access",
          toolUsed: "Spear Phishing",
          userUsed: "finance.user",
          timestamp: "2024-01-15T08:30:00Z",
          mitreAttackId: "T1566.001",
          description: "Delivered ransomware via phishing email",
        },
      },
      {
        id: "e-workstation-fileserver",
        source: "workstation-1",
        target: "file-server-1",
        type: "customEdge",
        data: {
          label: "Lateral Movement",
          actionType: "Lateral Movement",
          toolUsed: "Stolen Credentials",
          userUsed: "finance.user",
          timestamp: "2024-01-15T09:15:00Z",
          mitreAttackId: "T1021.002",
          description: "Used stolen credentials to access file server",
        },
      },
      {
        id: "e-fileserver-dc",
        source: "file-server-1",
        target: "domain-controller-1",
        type: "customEdge",
        data: {
          label: "Privilege Escalation",
          actionType: "Privilege Escalation",
          toolUsed: "Mimikatz",
          userUsed: "SYSTEM",
          timestamp: "2024-01-15T10:00:00Z",
          mitreAttackId: "T1003.001",
          description: "Extracted domain admin credentials",
        },
      },
              {
          id: "e-fileserver-cloud-storage",
          source: "file-server-1",
          target: "cloud-storage-1",
          type: "customEdge",
          data: {
            label: "Data Exfiltration",
            actionType: "Exfiltration",
            toolUsed: "Rclone",
            userUsed: "SYSTEM",
            timestamp: "2024-01-15T11:30:00Z",
            mitreAttackId: "T1041",
            description: "Exfiltrated sensitive data to cloud storage before encryption",
          },
        },
     ],
   },

     // Supply Chain Attack
  {
    id: "supply-chain-attack",
    name: "Software Supply Chain Attack",
    description: "Compromise through malicious software update in development pipeline",
    category: "Supply Chain",
    tags: ["supply-chain", "ci-cd", "development", "malware", "intermediate", "cloud"],
    createdAt: "2024-01-01T00:00:00Z",
    isBuiltIn: true,
    incidentLog: [
      {
        id: "incident-supply-chain-attack-1",
        timestamp: "2024-01-15T08:15:00Z",
        description: "Initial triage completed; scoped affected assets and logged findings.",
        category: "Observation",
      },
    ],
     nodes: [
       {
         id: "attacker-2",
         type: "customNode",
         position: { x: 50, y: 200 },
         data: {
           label: "Attacker Infrastructure",
           type: "attacker",
           criticality: "Critical",
           services: ["C2 Server", "Malware Repository"],
           actions: [
             {
               id: "action-1",
               type: "Initial Access",
               technique: "Supply Chain Compromise",
               details: "Compromised third-party software package",
             },
           ],
           description: "External attacker infrastructure",
           displaySettings: { ...defaultDisplaySettings },
           isCompromised: false,
    investigationStatus: "No Status",
         },
       },
               {
          id: "ci-cd-1",
          type: "customNode",
          position: { x: 300, y: 100 },
          data: {
            label: "CI/CD Pipeline",
            type: "cloud-instance",
            hostname: "jenkins.company.com",
            ipAddress: "10.0.3.10",
            os: "Ubuntu 20.04",
            criticality: "High",
            services: ["Jenkins", "Docker", "Git"],
            actions: [
              {
                id: "action-2",
                type: "Initial Access",
                technique: "Malicious Package",
                details: "Deployed malicious dependency in build process",
              },
            ],
            description: "Cloud-hosted continuous integration pipeline",
            displaySettings: { ...defaultDisplaySettings },
            isCompromised: true,
    investigationStatus: "No Status",
          },
        },
               {
          id: "dev-server-1",
          type: "customNode",
          position: { x: 550, y: 100 },
          data: {
            label: "Development Server",
            type: "cloud-instance",
            hostname: "dev-app.company.com",
            ipAddress: "10.0.3.20",
            os: "Ubuntu 20.04",
            criticality: "Medium",
            services: ["Node.js", "MongoDB", "Redis"],
            actions: [
              {
                id: "action-3",
                type: "Lateral Movement",
                technique: "Software Deployment",
                details: "Malicious code deployed to development environment",
              },
            ],
            description: "Cloud-hosted development application server",
            displaySettings: { ...defaultDisplaySettings },
            isCompromised: true,
    investigationStatus: "No Status",
          },
        },
               {
          id: "prod-server-1",
          type: "customNode",
          position: { x: 800, y: 100 },
         data: {
            label: "Production Server",
            type: "cloud-instance",
            hostname: "app.company.com",
            ipAddress: "10.0.1.30",
            os: "Ubuntu 20.04",
            criticality: "Critical",
            services: ["HTTP", "HTTPS", "MongoDB"],
            actions: [
              {
                id: "action-4",
                type: "Lateral Movement",
                technique: "Software Deployment",
                details: "Malicious code deployed to production environment",
              },
            ],
            description: "Cloud-hosted production application server",
            displaySettings: { ...defaultDisplaySettings },
            isCompromised: true,
    investigationStatus: "No Status",
          },
        },
               {
          id: "database-2",
          type: "customNode",
          position: { x: 1050, y: 100 },
          data: {
            label: "Production Database",
            type: "cloud-database",
            hostname: "db-prod-02",
            ipAddress: "10.0.1.40",
            os: "MongoDB 5.0",
            criticality: "Critical",
            services: ["MongoDB", "SSH"],
            actions: [
              {
                id: "action-5",
                type: "Collection",
                technique: "Data from Information Repositories",
                details: "Extracted customer data and application secrets",
              },
            ],
            description: "Cloud-hosted production database with customer data",
            displaySettings: { ...defaultDisplaySettings },
            isCompromised: true,
    investigationStatus: "No Status",
          },
        },
     ],
     edges: [
       {
         id: "e-attacker-cicd",
         source: "attacker-2",
         target: "ci-cd-1",
         type: "customEdge",
         data: {
           label: "Package Compromise",
           actionType: "Supply Chain Attack",
           toolUsed: "Malicious NPM Package",
           userUsed: "build-user",
           timestamp: "2024-01-15T14:00:00Z",
           mitreAttackId: "T1195.002",
           description: "Compromised third-party package in build process",
         },
       },
       {
         id: "e-cicd-dev",
         source: "ci-cd-1",
         target: "dev-server-1",
         type: "customEdge",
         data: {
           label: "Deploy to Dev",
           actionType: "Lateral Movement",
           toolUsed: "Jenkins Pipeline",
           userUsed: "jenkins",
           timestamp: "2024-01-15T14:30:00Z",
           mitreAttackId: "T1078",
           description: "Deployed malicious code to development environment",
         },
       },
       {
         id: "e-dev-prod",
         source: "dev-server-1",
         target: "prod-server-1",
         type: "customEdge",
         data: {
           label: "Deploy to Production",
           actionType: "Lateral Movement",
           toolUsed: "Automated Deployment",
           userUsed: "deploy-user",
           timestamp: "2024-01-15T15:00:00Z",
           mitreAttackId: "T1078",
           description: "Deployed malicious code to production environment",
         },
       },
       {
         id: "e-prod-db",
         source: "prod-server-1",
         target: "database-2",
         type: "customEdge",
         data: {
           label: "Database Access",
           actionType: "Lateral Movement",
           toolUsed: "Application Credentials",
           userUsed: "app-service",
           timestamp: "2024-01-15T15:15:00Z",
           mitreAttackId: "T1078",
           description: "Accessed production database with application credentials",
         },
       },
     ],
   },

     // APT Command & Control
  {
    id: "apt-c2-attack",
    name: "APT Command & Control Infrastructure",
    description: "Advanced Persistent Threat with sophisticated C2 infrastructure and persistence",
    category: "APT",
    tags: ["apt", "command-control", "persistence", "advanced", "nation-state", "cloud"],
    createdAt: "2024-01-01T00:00:00Z",
    isBuiltIn: true,
    incidentLog: [
      {
        id: "incident-apt-c2-attack-1",
        timestamp: "2024-01-15T08:15:00Z",
        description: "Initial triage completed; scoped affected assets and logged findings.",
        category: "Observation",
      },
    ],
     nodes: [
       {
         id: "attacker-3",
         type: "customNode",
         position: { x: 50, y: 200 },
         data: {
           label: "APT Infrastructure",
           type: "attacker",
           criticality: "Critical",
           services: ["C2 Servers", "Exfiltration Servers"],
           actions: [
             {
               id: "action-1",
               type: "Initial Access",
               technique: "Spear Phishing",
               details: "Targeted spear-phishing campaign against executives",
             },
           ],
           description: "Nation-state APT infrastructure",
           displaySettings: { ...defaultDisplaySettings },
           isCompromised: false,
    investigationStatus: "No Status",
         },
       },
       {
         id: "executive-1",
         type: "customNode",
         position: { x: 300, y: 100 },
         data: {
           label: "Executive Workstation",
           type: "workstation",
           hostname: "WS-EXEC-01",
           ipAddress: "10.0.2.10",
           os: "Windows 11 Pro",
           criticality: "High",
           services: ["RDP", "SMB", "HTTP", "Outlook"],
           actions: [
             {
               id: "action-2",
               type: "Initial Access",
               technique: "User Execution",
               details: "Executive opened malicious attachment from spear-phishing email",
             },
           ],
           description: "CEO workstation with high privileges",
           displaySettings: { ...defaultDisplaySettings },
           isCompromised: true,
    investigationStatus: "No Status",
         },
       },
       {
         id: "c2-server-1",
         type: "customNode",
         position: { x: 550, y: 100 },
         data: {
           label: "Command & Control",
           type: "command-control",
           criticality: "Critical",
           services: ["HTTP/HTTPS", "DNS", "ICMP"],
           actions: [
             {
               id: "action-3",
               type: "Command and Control",
               technique: "Multi-Channel C2",
               details: "Established multiple C2 channels for redundancy",
             },
           ],
           description: "Primary C2 infrastructure",
           displaySettings: { ...defaultDisplaySettings },
           commandControlData: {
             c2Type: "HTTP/HTTPS",
             c2Server: "legitimate-looking.com",
             c2Protocol: "HTTPS",
             beaconInterval: "Random 5-15m",
             jitter: 30,
             implantType: "Custom APT Malware",
             encryption: true,
             obfuscation: ["Domain Fronting", "Fast Flux", "DGA"],
             fallbackChannels: ["backup-c2.com", "twitter.com/legitimate"],
             killSwitchEnabled: true,
             persistenceMethods: ["Registry", "Scheduled Task", "Service"],
             operationalStatus: "Active",
           },
           isCompromised: true,
    investigationStatus: "No Status",
         },
       },
       {
         id: "domain-controller-2",
         type: "customNode",
         position: { x: 800, y: 100 },
         data: {
           label: "Domain Controller",
           type: "domain-controller",
           hostname: "DC-PRIMARY",
           ipAddress: "10.0.1.10",
           os: "Windows Server 2019",
           criticality: "Critical",
           services: ["AD DS", "DNS", "LDAP", "Kerberos"],
           actions: [
             {
               id: "action-4",
               type: "Privilege Escalation",
               technique: "Golden Ticket",
               details: "Created golden ticket for persistent domain access",
             },
           ],
           description: "Primary domain controller",
           displaySettings: { ...defaultDisplaySettings },
           isCompromised: true,
    investigationStatus: "No Status",
         },
       },
       {
         id: "file-server-2",
         type: "customNode",
         position: { x: 1050, y: 100 },
         data: {
           label: "File Server",
           type: "file-server",
           hostname: "FS-PROD-02",
           ipAddress: "10.0.1.25",
           os: "Windows Server 2019",
           criticality: "High",
           services: ["SMB", "RDP", "AD"],
           actions: [
             {
               id: "action-5",
               type: "Collection",
               technique: "Data from Network Shared Drive",
               details: "Collected sensitive documents and intellectual property",
             },
           ],
           description: "File server with sensitive documents",
           displaySettings: { ...defaultDisplaySettings },
           isCompromised: true,
    investigationStatus: "No Status",
         },
       },
               {
          id: "cloud-storage-2",
          type: "customNode",
          position: { x: 800, y: 300 },
          data: {
            label: "Cloud Storage",
            type: "cloud-storage",
            hostname: "apt-storage-bucket",
            ipAddress: "cloud-storage.com",
            os: "Cloud Storage",
            criticality: "Critical",
            services: ["HTTPS", "DNS Tunneling"],
            actions: [
              {
                id: "action-6",
                type: "Exfiltration",
                technique: "Exfiltration Over Alternative Protocol",
                details: "Exfiltrated data using DNS tunneling and cloud storage",
              },
            ],
            description: "APT-controlled cloud storage for stealthy data exfiltration",
            displaySettings: { ...defaultDisplaySettings },
            isCompromised: true,
    investigationStatus: "No Status",
          },
        },
     ],
     edges: [
       {
         id: "e-attacker-executive",
         source: "attacker-3",
         target: "executive-1",
         type: "customEdge",
         data: {
           label: "Spear Phishing",
           actionType: "Initial Access",
           toolUsed: "Spear Phishing",
           userUsed: "ceo@company.com",
           timestamp: "2024-01-15T16:00:00Z",
           mitreAttackId: "T1566.001",
           description: "Targeted spear-phishing attack against CEO",
         },
       },
       {
         id: "e-executive-c2",
         source: "executive-1",
         target: "c2-server-1",
         type: "customEdge",
         data: {
           label: "C2 Establishment",
           actionType: "Command & Control",
           toolUsed: "Custom APT Malware",
           userUsed: "SYSTEM",
           timestamp: "2024-01-15T16:15:00Z",
           mitreAttackId: "T1071.001",
           description: "Established command and control channel",
         },
       },
       {
         id: "e-c2-dc",
         source: "c2-server-1",
         target: "domain-controller-2",
         type: "customEdge",
         data: {
           label: "Domain Compromise",
           actionType: "Privilege Escalation",
           toolUsed: "Mimikatz",
           userUsed: "SYSTEM",
           timestamp: "2024-01-15T16:30:00Z",
           mitreAttackId: "T1003.001",
           description: "Extracted domain admin credentials and created golden ticket",
         },
       },
       {
         id: "e-dc-fileserver",
         source: "domain-controller-2",
         target: "file-server-2",
         type: "customEdge",
         data: {
           label: "File Server Access",
           actionType: "Lateral Movement",
           toolUsed: "Domain Admin Credentials",
           userUsed: "Domain Admin",
           timestamp: "2024-01-15T16:45:00Z",
           mitreAttackId: "T1021.002",
           description: "Accessed file server with domain admin privileges",
         },
       },
               {
          id: "e-fileserver-cloud-storage-2",
          source: "file-server-2",
          target: "cloud-storage-2",
          type: "customEdge",
          data: {
            label: "Data Exfiltration",
            actionType: "Exfiltration",
            toolUsed: "DNS Tunneling",
            userUsed: "SYSTEM",
            timestamp: "2024-01-15T17:00:00Z",
            mitreAttackId: "T1048.003",
            description: "Exfiltrated sensitive data to cloud storage using DNS tunneling",
          },
        },
     ],
   },

   // Cloud Infrastructure Attack
   {
     id: "cloud-infrastructure-attack",
     name: "Cloud Infrastructure Compromise",
     description: "Attack targeting cloud infrastructure through misconfigured services",
     category: "Cloud Security",
     tags: ["cloud", "aws", "misconfiguration", "privilege-escalation", "intermediate"],
    createdAt: "2024-01-01T00:00:00Z",
     isBuiltIn: true,
     incidentLog: [
       {
         id: "incident-cloud-infrastructure-attack-1",
         timestamp: "2024-01-15T08:15:00Z",
         description: "Initial triage completed; scoped affected assets and logged findings.",
         category: "Observation",
       },
     ],
     nodes: [
       {
         id: "attacker-4",
         type: "customNode",
         position: { x: 50, y: 200 },
         data: {
           label: "Attacker Infrastructure",
           type: "attacker",
           criticality: "Critical",
           services: ["C2 Server", "Exfiltration Server"],
           actions: [
             {
               id: "action-1",
               type: "Initial Access",
               technique: "Cloud Service Discovery",
               details: "Discovered exposed cloud services through reconnaissance",
             },
           ],
           description: "External attacker infrastructure",
           displaySettings: { ...defaultDisplaySettings },
           isCompromised: false,
    investigationStatus: "No Status",
         },
       },
       {
         id: "s3-bucket-1",
         type: "customNode",
         position: { x: 300, y: 100 },
         data: {
           label: "Exposed S3 Bucket",
           type: "other",
           hostname: "company-data-bucket",
           ipAddress: "s3.amazonaws.com",
           os: "AWS S3",
           criticality: "High",
           services: ["S3", "HTTP", "HTTPS"],
           actions: [
             {
               id: "action-2",
               type: "Initial Access",
               technique: "Cloud Service Misconfiguration",
               details: "Exploited publicly accessible S3 bucket",
             },
           ],
           description: "Misconfigured S3 bucket with sensitive data",
           displaySettings: { ...defaultDisplaySettings },
           isCompromised: true,
    investigationStatus: "No Status",
         },
       },
       {
         id: "ec2-instance-1",
         type: "customNode",
         position: { x: 550, y: 100 },
         data: {
           label: "EC2 Instance",
           type: "workstation",
           hostname: "web-server-01",
           ipAddress: "10.0.1.100",
           os: "Amazon Linux 2",
           criticality: "Medium",
           services: ["HTTP", "HTTPS", "SSH"],
           actions: [
             {
               id: "action-3",
               type: "Lateral Movement",
               technique: "Cloud Instance Metadata",
               details: "Extracted IAM credentials from instance metadata",
             },
           ],
           description: "Web server EC2 instance",
           displaySettings: { ...defaultDisplaySettings },
           isCompromised: true,
    investigationStatus: "No Status",
         },
       },
       {
         id: "iam-role-1",
         type: "customNode",
         position: { x: 800, y: 100 },
         data: {
           label: "IAM Role",
           type: "identity",
           criticality: "Critical",
           services: ["AWS IAM"],
           actions: [
             {
               id: "action-4",
               type: "Privilege Escalation",
               technique: "Cloud Role Abuse",
               details: "Abused over-privileged IAM role",
             },
           ],
           description: "Over-privileged IAM role",
           displaySettings: { ...defaultDisplaySettings },
           identityData: {
             username: "web-server-role",
             domain: "aws.amazon.com",
             accountType: "Service",
             accountSource: "Cloud",
             privileges: ["S3FullAccess", "EC2FullAccess", "IAMReadAccess"],
             groups: ["WebServerRole"],
             accountStatus: "Active",
             mfaEnabled: false,
             riskLevel: "High",
           },
           isCompromised: true,
    investigationStatus: "No Status",
         },
       },
       {
         id: "rds-instance-1",
         type: "customNode",
         position: { x: 1050, y: 100 },
         data: {
           label: "RDS Database",
           type: "database",
           hostname: "prod-database",
           ipAddress: "10.0.1.200",
           os: "PostgreSQL 13",
           criticality: "Critical",
           services: ["PostgreSQL", "SSL"],
           actions: [
             {
               id: "action-5",
               type: "Collection",
               technique: "Data from Cloud Storage",
               details: "Accessed production database with stolen credentials",
             },
           ],
           description: "Production RDS database",
           displaySettings: { ...defaultDisplaySettings },
           isCompromised: true,
    investigationStatus: "No Status",
         },
       },
     ],
     edges: [
       {
         id: "e-attacker-s3",
         source: "attacker-4",
         target: "s3-bucket-1",
         type: "customEdge",
         data: {
           label: "S3 Access",
           actionType: "Initial Access",
           toolUsed: "AWS CLI",
           userUsed: "anonymous",
           timestamp: "2024-01-15T18:00:00Z",
           mitreAttackId: "T1530",
           description: "Accessed misconfigured S3 bucket",
         },
       },
       {
         id: "e-s3-ec2",
         source: "s3-bucket-1",
         target: "ec2-instance-1",
         type: "customEdge",
         data: {
           label: "Instance Access",
           actionType: "Lateral Movement",
           toolUsed: "SSH Key",
           userUsed: "ec2-user",
           timestamp: "2024-01-15T18:15:00Z",
           mitreAttackId: "T1021.004",
           description: "Used SSH key from S3 bucket to access EC2 instance",
         },
       },
       {
         id: "e-ec2-iam",
         source: "ec2-instance-1",
         target: "iam-role-1",
         type: "customEdge",
         data: {
           label: "IAM Compromise",
           actionType: "Privilege Escalation",
           toolUsed: "Instance Metadata",
           userUsed: "web-server-role",
           timestamp: "2024-01-15T18:30:00Z",
           mitreAttackId: "T1078.004",
           description: "Extracted IAM credentials from instance metadata",
         },
       },
       {
         id: "e-iam-rds",
         source: "iam-role-1",
         target: "rds-instance-1",
         type: "customEdge",
         data: {
           label: "Database Access",
           actionType: "Lateral Movement",
           toolUsed: "IAM Credentials",
           userUsed: "web-server-role",
           timestamp: "2024-01-15T18:45:00Z",
           mitreAttackId: "T1078.004",
           description: "Accessed RDS database with IAM credentials",
         },
       },
     ],
   },

     // Insider Threat
  {
    id: "insider-threat",
    name: "Insider Threat Attack",
    description: "Malicious insider using legitimate access for data theft",
    category: "Insider Threat",
    tags: ["insider", "data-theft", "privilege-abuse", "intermediate", "cloud"],
    createdAt: "2024-01-01T00:00:00Z",
    isBuiltIn: true,
    incidentLog: [
      {
        id: "incident-insider-threat-1",
        timestamp: "2024-01-15T08:15:00Z",
        description: "Initial triage completed; scoped affected assets and logged findings.",
        category: "Observation",
      },
    ],
     nodes: [
       {
         id: "insider-1",
         type: "customNode",
         position: { x: 100, y: 100 },
         data: {
           label: "Malicious Insider",
           type: "identity",
           criticality: "High",
           services: ["VPN", "Email", "File Access"],
           actions: [
             {
               id: "action-1",
               type: "Initial Access",
               technique: "Valid Accounts",
               details: "Used legitimate employee credentials",
             },
           ],
           description: "Disgruntled employee with elevated privileges",
           displaySettings: { ...defaultDisplaySettings },
           identityData: {
             username: "john.smith",
             domain: "company.com",
             accountType: "User",
             accountSource: "Hybrid",
             privileges: ["Finance Data Access", "HR Data Access", "Admin Rights"],
             groups: ["Finance Team", "IT Support"],
             accountStatus: "Active",
             mfaEnabled: true,
             riskLevel: "High",
           },
           isCompromised: true,
    investigationStatus: "No Status",
         },
       },
       {
         id: "workstation-2",
         type: "customNode",
         position: { x: 350, y: 100 },
         data: {
           label: "Employee Workstation",
           type: "workstation",
           hostname: "WS-FINANCE-02",
           ipAddress: "10.0.2.20",
           os: "Windows 11 Pro",
           criticality: "Medium",
           services: ["RDP", "SMB", "HTTP", "Outlook"],
           actions: [
             {
               id: "action-2",
               type: "Lateral Movement",
               technique: "Valid Accounts",
               details: "Logged into workstation with legitimate credentials",
             },
           ],
           description: "Finance department workstation",
           displaySettings: { ...defaultDisplaySettings },
           isCompromised: true,
    investigationStatus: "No Status",
         },
       },
               {
          id: "cloud-productivity-storage-2",
          type: "customNode",
          position: { x: 600, y: 100 },
          data: {
            label: "Cloud Productivity Storage",
            type: "cloud-productivity-storage",
            hostname: "company-storage.cloud.com",
            ipAddress: "cloud.provider.com",
            os: "Cloud Storage Service",
            criticality: "High",
            services: ["HTTPS", "REST API", "WebDAV"],
            actions: [
              {
                id: "action-3",
                type: "Collection",
                technique: "Data from Information Repositories",
                details: "Accessed sensitive financial and HR documents",
              },
            ],
            description: "Cloud storage with sensitive business data",
            displaySettings: { ...defaultDisplaySettings },
            isCompromised: true,
    investigationStatus: "No Status",
          },
        },
       {
         id: "exfiltration-3",
         type: "customNode",
         position: { x: 600, y: 300 },
         data: {
           label: "Data Exfiltration",
           type: "exfiltration",
           criticality: "Critical",
           services: ["Cloud Storage", "Email", "USB"],
           actions: [
             {
               id: "action-4",
               type: "Exfiltration",
               technique: "Exfiltration Over Physical Medium",
               details: "Copied data to personal cloud storage and USB devices",
             },
           ],
           description: "Data exfiltration to personal devices",
           displaySettings: { ...defaultDisplaySettings },
           exfiltrationData: {
             method: "Cloud Storage",
             destination: "personal-dropbox.com",
             protocol: "HTTPS",
             encryption: false,
             compression: false,
             dataTypes: ["Financial Records", "HR Data", "Customer PII"],
             volumeGB: 50,
             transferRate: "10 MB/s",
             detectionEvasion: ["Legitimate Service Abuse", "Off-hours Activity"],
             exfiltrationWindow: "After Hours",
             status: "Completed",
           },
           isCompromised: true,
    investigationStatus: "No Status",
         },
       },
     ],
     edges: [
       {
         id: "e-insider-workstation",
         source: "insider-1",
         target: "workstation-2",
         type: "customEdge",
         data: {
           label: "Workstation Access",
           actionType: "Initial Access",
           toolUsed: "Valid Credentials",
           userUsed: "john.smith",
           timestamp: "2024-01-15T19:00:00Z",
           mitreAttackId: "T1078",
           description: "Logged into workstation with legitimate credentials",
         },
       },
               {
          id: "e-workstation-cloud-storage",
          source: "workstation-2",
          target: "cloud-productivity-storage-2",
          type: "customEdge",
          data: {
            label: "Cloud Storage Access",
            actionType: "Lateral Movement",
            toolUsed: "Valid Credentials",
            userUsed: "john.smith",
            timestamp: "2024-01-15T19:15:00Z",
            mitreAttackId: "T1021.002",
            description: "Accessed cloud storage with legitimate access rights",
          },
        },
               {
          id: "e-cloud-storage-exfiltration",
          source: "cloud-productivity-storage-2",
          target: "exfiltration-3",
          type: "customEdge",
          data: {
            label: "Data Theft",
            actionType: "Exfiltration",
            toolUsed: "Cloud Storage",
            userUsed: "john.smith",
            timestamp: "2024-01-15T19:30:00Z",
            mitreAttackId: "T1041",
            description: "Copied sensitive data to personal cloud storage",
          },
        },
     ],
   },

   // Email Phishing Campaign
   {
     id: "simple-phishing-attack",
     name: "Email Phishing Campaign",
     description: "Basic phishing attack targeting user credentials through email compromise",
     category: "Social Engineering",
     tags: ["phishing", "email", "credentials", "beginner"],
    createdAt: "2024-01-01T00:00:00Z",
     isBuiltIn: true,
     incidentLog: [
       {
         id: "incident-simple-phishing-attack-1",
         timestamp: "2024-01-15T08:15:00Z",
         description: "Initial triage completed; scoped affected assets and logged findings.",
         category: "Observation",
       },
     ],
     nodes: [
       {
         id: "user-identity-1",
         type: "customNode",
         position: { x: 100, y: 100 },
         data: {
           label: "Marketing User",
           type: "identity",
           criticality: "Medium",
           services: [],
           actions: [
             {
               id: "action-1",
               type: "Initial Access",
               technique: "Phishing",
               details: "User clicked malicious link in phishing email and entered credentials",
             },
           ],
           description: "Marketing department employee targeted by phishing campaign",
           displaySettings: { ...defaultDisplaySettings },
           identityData: {
             username: "john.doe",
             domain: "company.com",
             accountType: "User",
             accountSource: "Cloud",
             privileges: ["Marketing Data Access"],
             groups: ["Marketing Team"],
             accountStatus: "Active",
             mfaEnabled: false,
             riskLevel: "Medium",
           },
           isCompromised: true,
    investigationStatus: "No Status",
         },
       },
       {
         id: "email-server-1",
         type: "customNode",
         position: { x: 400, y: 100 },
         data: {
           label: "Email Server",
           type: "email-server",
           hostname: "mail.company.com",
           ipAddress: "10.0.1.25",
           os: "Exchange Server 2019",
           criticality: "High",
           services: ["SMTP", "IMAP", "POP3", "HTTPS"],
           actions: [
             {
               id: "action-2",
               type: "Collection",
               technique: "Email Collection",
               details: "Accessed user's mailbox and downloaded email contacts and messages",
             },
           ],
           description: "Corporate email server containing business communications",
           displaySettings: { ...defaultDisplaySettings },
           isCompromised: true,
    investigationStatus: "No Status",
         },
       },
     ],
     edges: [
       {
         id: "e-user-email",
         source: "user-identity-1",
         target: "email-server-1",
         type: "customEdge",
         data: {
           label: "Email Access",
           actionType: "Lateral Movement",
           toolUsed: "Stolen Credentials",
           userUsed: "john.doe@company.com",
           timestamp: "2024-01-15T09:15:00Z",
           mitreAttackId: "T1078",
           description: "Used phished credentials to access corporate email account",
         },
       },
     ],
   },

   // Cloud Productivity Suite Attack
   {
     id: "cloud-productivity-attack",
     name: "Cloud Productivity Suite Compromise",
     description: "Attack targeting M365/Google Workspace through credential theft and API abuse",
     category: "Cloud Security",
     tags: ["m365", "google-workspace", "api-abuse", "credential-theft", "intermediate"],
    createdAt: "2024-01-01T00:00:00Z",
     isBuiltIn: true,
     incidentLog: [
       {
         id: "incident-cloud-productivity-attack-1",
         timestamp: "2024-01-15T08:15:00Z",
         description: "Initial triage completed; scoped affected assets and logged findings.",
         category: "Observation",
       },
     ],
     nodes: [
       {
         id: "attacker-5",
         type: "customNode",
         position: { x: 50, y: 200 },
         data: {
           label: "Attacker Infrastructure",
           type: "attacker",
           criticality: "Critical",
           services: ["C2 Server", "Exfiltration Server"],
           actions: [
             {
               id: "action-1",
               type: "Initial Access",
               technique: "Phishing with OAuth",
               details: "Targeted phishing campaign with OAuth consent screen",
             },
           ],
           description: "External attacker infrastructure",
           displaySettings: { ...defaultDisplaySettings },
           isCompromised: false,
    investigationStatus: "No Status",
         },
       },
       {
         id: "user-identity-2",
         type: "customNode",
         position: { x: 300, y: 100 },
         data: {
           label: "Compromised User",
           type: "identity",
           criticality: "Medium",
           services: ["M365", "Google Workspace"],
           actions: [
             {
               id: "action-2",
               type: "Initial Access",
               technique: "Valid Accounts",
               details: "User granted OAuth permissions to malicious app",
             },
           ],
           description: "User with access to cloud",
           displaySettings: { ...defaultDisplaySettings },
           identityData: {
             username: "jane.smith",
             domain: "company.com",
             accountType: "User",
             accountSource: "Cloud",
             privileges: ["M365 User", "Google Workspace User"],
             groups: ["Sales Team", "Marketing Team"],
             accountStatus: "Active",
             mfaEnabled: true,
             riskLevel: "Medium",
           },
           isCompromised: true,
    investigationStatus: "No Status",
         },
       },
               {
          id: "cloud-tenant-1",
          type: "customNode",
          position: { x: 550, y: 50 },
          data: {
            label: "Cloud Tenant",
            type: "cloud-tenant",
            criticality: "Critical",
            services: ["Identity Provider", "Email Service", "Storage Service"],
            actions: [
              {
                id: "action-3",
                type: "Lateral Movement",
                technique: "OAuth Token Abuse",
                details: "Used stolen OAuth tokens to access cloud APIs",
              },
            ],
            description: "Cloud productivity suite tenant with business data",
            displaySettings: { ...defaultDisplaySettings },
            cloudTenantData: {
              tenantId: "12345678-1234-1234-1234-123456789012",
              tenantName: "company.cloud.com",
              cloudProvider: "Azure",
              tenantType: "Entra ID",
              subscriptionId: "87654321-4321-4321-4321-210987654321",
              region: "eastus",
              environment: "Production",
              resourceCount: 150,
              securityScore: 85,
            },
            isCompromised: true,
    investigationStatus: "No Status",
          },
        },
               {
          id: "cloud-email-1",
          type: "customNode",
          position: { x: 800, y: 50 },
          data: {
            label: "Cloud Email",
            type: "cloud-email",
            hostname: "mail.cloud.com",
            ipAddress: "cloud.provider.com",
            os: "Cloud Email Service",
            criticality: "High",
            services: ["SMTP", "IMAP", "REST API"],
            actions: [
              {
                id: "action-4",
                type: "Collection",
                technique: "Email Collection",
                details: "Accessed user mailboxes via cloud API",
              },
            ],
            description: "Cloud email and messaging service",
            displaySettings: { ...defaultDisplaySettings },
            isCompromised: true,
    investigationStatus: "No Status",
          },
        },
               {
          id: "cloud-productivity-storage-1",
          type: "customNode",
          position: { x: 800, y: 150 },
          data: {
            label: "Cloud Productivity Storage",
            type: "cloud-productivity-storage",
            hostname: "storage.cloud.com",
            ipAddress: "cloud.provider.com",
            os: "Cloud Storage Service",
            criticality: "High",
            services: ["HTTP", "HTTPS", "REST API"],
            actions: [
              {
                id: "action-5",
                type: "Collection",
                technique: "Data from Information Repositories",
                details: "Accessed cloud storage and document libraries",
              },
            ],
            description: "Cloud document management and collaboration",
            displaySettings: { ...defaultDisplaySettings },
            isCompromised: true,
    investigationStatus: "No Status",
          },
        },
               {
          id: "cloud-tenant-2",
          type: "customNode",
          position: { x: 550, y: 250 },
          data: {
            label: "Cloud Tenant 2",
            type: "cloud-tenant",
            criticality: "Critical",
            services: ["Identity Provider", "Email Service", "Storage Service"],
            actions: [
              {
                id: "action-6",
                type: "Lateral Movement",
                technique: "OAuth Token Abuse",
                details: "Used stolen OAuth tokens to access cloud APIs",
              },
            ],
            description: "Second cloud tenant",
            displaySettings: { ...defaultDisplaySettings },
            cloudTenantData: {
              tenantId: "87654321-4321-4321-4321-210987654321",
              tenantName: "company2.cloud.com",
              cloudProvider: "AWS",
              tenantType: "AWS Organizations",
              accountId: "123456789012",
              region: "us-east-1",
              environment: "Production",
              resourceCount: 200,
              securityScore: 92,
            },
            isCompromised: true,
    investigationStatus: "No Status",
          },
        },
               {
          id: "cloud-email-2",
          type: "customNode",
          position: { x: 800, y: 250 },
          data: {
            label: "Cloud Email 2",
            type: "cloud-email",
            hostname: "mail2.cloud.com",
            ipAddress: "cloud2.provider.com",
            os: "Cloud Email Service",
            criticality: "High",
            services: ["SMTP", "IMAP", "REST API"],
            actions: [
              {
                id: "action-7",
                type: "Collection",
                technique: "Email Collection",
                details: "Accessed cloud email accounts via API",
              },
            ],
            description: "Second cloud email service",
            displaySettings: { ...defaultDisplaySettings },
            isCompromised: true,
    investigationStatus: "No Status",
          },
        },
       {
         id: "exfiltration-4",
         type: "customNode",
         position: { x: 1050, y: 150 },
         data: {
           label: "Data Exfiltration",
           type: "exfiltration",
           criticality: "Critical",
           services: ["Cloud Storage", "API"],
           actions: [
             {
               id: "action-8",
               type: "Exfiltration",
               technique: "Exfiltration Over Web Service",
               details: "Exfiltrated emails and documents via API calls",
             },
           ],
           description: "Data exfiltration from cloud productivity suites",
           displaySettings: { ...defaultDisplaySettings },
           exfiltrationData: {
             method: "HTTP/HTTPS",
             destination: "attacker-server.com/api",
             protocol: "HTTPS",
             encryption: true,
             compression: false,
             dataTypes: ["Emails", "Documents", "Calendar Data", "Contacts"],
             volumeGB: 25,
             transferRate: "5 MB/s",
             detectionEvasion: ["API Rate Limiting", "Legitimate Service Abuse"],
             exfiltrationWindow: "Business Hours Only",
             status: "In Progress",
           },
           isCompromised: true,
    investigationStatus: "No Status",
         },
       },
     ],
     edges: [
       {
         id: "e-attacker-user",
         source: "attacker-5",
         target: "user-identity-2",
         type: "customEdge",
         data: {
           label: "OAuth Phishing",
           actionType: "Initial Access",
           toolUsed: "Phishing Campaign",
           userUsed: "jane.smith",
           timestamp: "2024-01-15T20:00:00Z",
           mitreAttackId: "T1566.001",
           description: "User granted OAuth permissions to malicious application",
         },
       },
               {
          id: "e-user-cloud-tenant",
          source: "user-identity-2",
          target: "cloud-tenant-1",
          type: "customEdge",
          data: {
            label: "Cloud Tenant Access",
            actionType: "Lateral Movement",
            toolUsed: "OAuth Tokens",
            userUsed: "jane.smith",
            timestamp: "2024-01-15T20:15:00Z",
            mitreAttackId: "T1078.004",
            description: "Used OAuth tokens to access cloud tenant",
          },
        },
               {
          id: "e-cloud-tenant-email",
          source: "cloud-tenant-1",
          target: "cloud-email-1",
          type: "customEdge",
          data: {
            label: "Cloud Email Access",
            actionType: "Lateral Movement",
            toolUsed: "Cloud API",
            userUsed: "jane.smith",
            timestamp: "2024-01-15T20:30:00Z",
            mitreAttackId: "T1078.004",
            description: "Accessed cloud email via API",
          },
        },
               {
          id: "e-cloud-tenant-storage",
          source: "cloud-tenant-1",
          target: "cloud-productivity-storage-1",
          type: "customEdge",
          data: {
            label: "Cloud Storage Access",
            actionType: "Lateral Movement",
            toolUsed: "Cloud API",
            userUsed: "jane.smith",
            timestamp: "2024-01-15T20:45:00Z",
            mitreAttackId: "T1078.004",
            description: "Accessed cloud storage via API",
          },
        },
               {
          id: "e-user-cloud-tenant-2",
          source: "user-identity-2",
          target: "cloud-tenant-2",
          type: "customEdge",
          data: {
            label: "Cloud Tenant 2 Access",
            actionType: "Lateral Movement",
            toolUsed: "OAuth Tokens",
            userUsed: "jane.smith",
            timestamp: "2024-01-15T21:00:00Z",
            mitreAttackId: "T1078.004",
            description: "Used OAuth tokens to access second cloud tenant",
          },
        },
               {
          id: "e-cloud-tenant-2-email",
          source: "cloud-tenant-2",
          target: "cloud-email-2",
          type: "customEdge",
          data: {
            label: "Cloud Email 2 Access",
            actionType: "Lateral Movement",
            toolUsed: "Cloud API",
            userUsed: "jane.smith",
            timestamp: "2024-01-15T21:15:00Z",
            mitreAttackId: "T1078.004",
            description: "Accessed second cloud email via API",
          },
        },
               {
          id: "e-cloud-email-exfiltration",
          source: "cloud-email-1",
          target: "exfiltration-4",
          type: "customEdge",
          data: {
            label: "Cloud Email Exfiltration",
            actionType: "Exfiltration",
            toolUsed: "Cloud API",
            userUsed: "jane.smith",
            timestamp: "2024-01-15T21:30:00Z",
            mitreAttackId: "T1041",
            description: "Exfiltrated emails via API calls",
          },
        },
               {
          id: "e-cloud-storage-exfiltration",
          source: "cloud-productivity-storage-1",
          target: "exfiltration-4",
          type: "customEdge",
          data: {
            label: "Cloud Storage Exfiltration",
            actionType: "Exfiltration",
            toolUsed: "Cloud API",
            userUsed: "jane.smith",
            timestamp: "2024-01-15T21:45:00Z",
            mitreAttackId: "T1041",
            description: "Exfiltrated documents via API calls",
          },
        },
               {
          id: "e-cloud-email-2-exfiltration",
          source: "cloud-email-2",
          target: "exfiltration-4",
          type: "customEdge",
          data: {
            label: "Cloud Email 2 Exfiltration",
            actionType: "Exfiltration",
            toolUsed: "Cloud API",
            userUsed: "jane.smith",
            timestamp: "2024-01-15T22:00:00Z",
            mitreAttackId: "T1041",
            description: "Exfiltrated cloud email data via API calls",
          },
        },
     ],
   },

   // Cloud-Native Attack
   {
     id: "cloud-native-attack",
     name: "Cloud-Native Infrastructure Attack",
     description: "Attack targeting modern cloud-native infrastructure with containers and serverless",
     category: "Cloud Security",
     tags: ["cloud-native", "containers", "serverless", "kubernetes", "advanced"],
    createdAt: "2024-01-01T00:00:00Z",
     isBuiltIn: true,
     incidentLog: [
       {
         id: "incident-cloud-native-attack-1",
         timestamp: "2024-01-15T08:15:00Z",
         description: "Initial triage completed; scoped affected assets and logged findings.",
         category: "Observation",
       },
     ],
     nodes: [
       {
         id: "attacker-6",
         type: "customNode",
         position: { x: 50, y: 200 },
         data: {
           label: "Attacker Infrastructure",
           type: "attacker",
           criticality: "Critical",
           services: ["C2 Server", "Exfiltration Server"],
           actions: [
             {
               id: "action-1",
               type: "Initial Access",
               technique: "Cloud Service Discovery",
               details: "Discovered exposed cloud-native services through reconnaissance",
             },
           ],
           description: "External attacker infrastructure",
           displaySettings: { ...defaultDisplaySettings },
           isCompromised: false,
    investigationStatus: "No Status",
         },
       },
       {
         id: "cloud-load-balancer-1",
         type: "customNode",
         position: { x: 300, y: 100 },
         data: {
           label: "Cloud Load Balancer",
           type: "cloud-load-balancer",
           hostname: "lb-prod.company.com",
           ipAddress: "cloud.provider.com",
           os: "Cloud Load Balancer",
           criticality: "High",
           services: ["HTTP", "HTTPS", "Health Checks"],
           actions: [
             {
               id: "action-2",
               type: "Initial Access",
               technique: "Cloud Service Misconfiguration",
               details: "Exploited misconfigured load balancer security groups",
             },
           ],
           description: "Public-facing load balancer for containerized applications",
           displaySettings: { ...defaultDisplaySettings },
           isCompromised: true,
    investigationStatus: "No Status",
         },
       },
       {
         id: "kubernetes-cluster-1",
         type: "customNode",
         position: { x: 550, y: 100 },
         data: {
           label: "Kubernetes Cluster",
           type: "cloud-kubernetes",
           hostname: "k8s-prod-cluster",
           ipAddress: "10.0.1.100",
           os: "Kubernetes 1.24",
           criticality: "Critical",
           services: ["kubelet", "kube-apiserver", "etcd"],
           actions: [
             {
               id: "action-3",
               type: "Lateral Movement",
               technique: "Container Escape",
               details: "Escaped container to access Kubernetes cluster",
             },
           ],
           description: "Production Kubernetes cluster running containerized applications",
           displaySettings: { ...defaultDisplaySettings },
           isCompromised: true,
    investigationStatus: "No Status",
         },
       },
       {
         id: "container-1",
         type: "customNode",
         position: { x: 800, y: 100 },
         data: {
           label: "Containerized App",
           type: "cloud-container",
           hostname: "app-container-01",
           ipAddress: "10.0.1.101",
           os: "Alpine Linux",
           criticality: "Medium",
           services: ["HTTP", "Node.js", "Redis"],
           actions: [
             {
               id: "action-4",
               type: "Lateral Movement",
               technique: "Container Escape",
               details: "Escaped container to access host system",
             },
           ],
           description: "Containerized web application with elevated privileges",
           displaySettings: { ...defaultDisplaySettings },
           isCompromised: true,
    investigationStatus: "No Status",
         },
       },
       {
         id: "serverless-function-1",
         type: "customNode",
         position: { x: 800, y: 200 },
         data: {
           label: "Serverless Function",
           type: "cloud-function",
           hostname: "lambda-function-01",
           ipAddress: "lambda.provider.com",
           os: "AWS Lambda",
           criticality: "Medium",
           services: ["HTTP", "Lambda Runtime"],
           actions: [
             {
               id: "action-5",
               type: "Lateral Movement",
               technique: "Serverless Function Abuse",
               details: "Abused serverless function to access other cloud services",
             },
           ],
           description: "Serverless function with access to cloud resources",
           displaySettings: { ...defaultDisplaySettings },
           isCompromised: true,
    investigationStatus: "No Status",
         },
       },
       {
         id: "cloud-database-1",
         type: "customNode",
         position: { x: 1050, y: 100 },
         data: {
           label: "Cloud Database",
           type: "cloud-database",
           hostname: "rds-prod-db",
           ipAddress: "10.0.1.200",
           os: "PostgreSQL 14",
           criticality: "Critical",
           services: ["PostgreSQL", "SSL"],
           actions: [
             {
               id: "action-6",
               type: "Collection",
               technique: "Data from Cloud Storage",
               details: "Accessed production database with stolen credentials",
             },
           ],
           description: "Cloud-managed database with sensitive application data",
           displaySettings: { ...defaultDisplaySettings },
           isCompromised: true,
    investigationStatus: "No Status",
         },
       },
       {
         id: "cloud-storage-3",
         type: "customNode",
         position: { x: 1050, y: 200 },
         data: {
           label: "Cloud Storage",
           type: "cloud-storage",
           hostname: "backup-bucket",
           ipAddress: "s3.amazonaws.com",
           os: "AWS S3",
           criticality: "High",
           services: ["S3", "HTTPS"],
           actions: [
             {
               id: "action-7",
               type: "Exfiltration",
               technique: "Data Transfer Size Limits",
               details: "Exfiltrated database backups and application data",
             },
           ],
           description: "Cloud storage containing database backups and application data",
           displaySettings: { ...defaultDisplaySettings },
           isCompromised: true,
    investigationStatus: "No Status",
         },
       },
     ],
     edges: [
       {
         id: "e-attacker-load-balancer",
         source: "attacker-6",
         target: "cloud-load-balancer-1",
         type: "customEdge",
         data: {
           label: "Load Balancer Access",
           actionType: "Initial Access",
           toolUsed: "Network Scanning",
           userUsed: "anonymous",
           timestamp: "2024-01-15T23:00:00Z",
           mitreAttackId: "T1590",
           description: "Discovered and accessed misconfigured load balancer",
         },
       },
       {
         id: "e-load-balancer-k8s",
         source: "cloud-load-balancer-1",
         target: "kubernetes-cluster-1",
         type: "customEdge",
         data: {
           label: "Kubernetes Access",
           actionType: "Lateral Movement",
           toolUsed: "kubectl",
           userUsed: "anonymous",
           timestamp: "2024-01-15T23:15:00Z",
           mitreAttackId: "T1610",
           description: "Accessed Kubernetes cluster through load balancer",
         },
       },
       {
         id: "e-k8s-container",
         source: "kubernetes-cluster-1",
         target: "container-1",
         type: "customEdge",
         data: {
           label: "Container Escape",
           actionType: "Lateral Movement",
           toolUsed: "Container Escape",
           userUsed: "root",
           timestamp: "2024-01-15T23:30:00Z",
           mitreAttackId: "T1611",
           description: "Escaped container to access host system",
         },
       },
       {
         id: "e-k8s-serverless",
         source: "kubernetes-cluster-1",
         target: "serverless-function-1",
         type: "customEdge",
         data: {
           label: "Serverless Access",
           actionType: "Lateral Movement",
           toolUsed: "Cloud API",
           userUsed: "k8s-service-account",
           timestamp: "2024-01-15T23:45:00Z",
           mitreAttackId: "T1078.004",
           description: "Accessed serverless function using Kubernetes service account",
         },
       },
       {
         id: "e-serverless-database",
         source: "serverless-function-1",
         target: "cloud-database-1",
         type: "customEdge",
         data: {
           label: "Database Access",
           actionType: "Lateral Movement",
           toolUsed: "Database Credentials",
           userUsed: "lambda-function",
           timestamp: "2024-01-16T00:00:00Z",
           mitreAttackId: "T1078.004",
           description: "Accessed cloud database using serverless function credentials",
         },
       },
       {
         id: "e-container-database",
         source: "container-1",
         target: "cloud-database-1",
         type: "customEdge",
         data: {
           label: "Database Access",
           actionType: "Lateral Movement",
           toolUsed: "Database Credentials",
           userUsed: "container-user",
           timestamp: "2024-01-16T00:15:00Z",
           mitreAttackId: "T1078.004",
           description: "Accessed cloud database from compromised container",
         },
       },
       {
         id: "e-database-storage",
         source: "cloud-database-1",
         target: "cloud-storage-3",
         type: "customEdge",
         data: {
           label: "Backup Access",
           actionType: "Lateral Movement",
           toolUsed: "Database Credentials",
           userUsed: "db-service",
           timestamp: "2024-01-16T00:30:00Z",
           mitreAttackId: "T1078.004",
           description: "Accessed cloud storage containing database backups",
         },
       },
       {
         id: "e-storage-exfiltration",
         source: "cloud-storage-3",
         target: "attacker-6",
         type: "customEdge",
         data: {
           label: "Data Exfiltration",
           actionType: "Exfiltration",
           toolUsed: "Cloud API",
           userUsed: "anonymous",
           timestamp: "2024-01-16T00:45:00Z",
           mitreAttackId: "T1041",
           description: "Exfiltrated database backups and application data",
         },
       },
     ],
   },
   {
     id: "multi-tenant-cloud-attack",
     name: "Multi-Tenant Cloud Identity Attack",
     description: "Attack targeting multiple cloud identity providers and tenants",
     category: "Cloud Security",
     tags: ["multi-tenant", "identity", "cloud", "oauth", "advanced"],
     createdAt: "2024-01-01T00:00:00Z",
     isBuiltIn: true,
     incidentLog: [
       {
         id: "incident-mt-1",
         timestamp: "2024-01-16T08:30:00Z",
         description: "Detected anomalous OAuth token usage across tenants; initiated triage with identity team.",
         category: "Observation",
       },
       {
         id: "incident-mt-2",
         timestamp: "2024-01-16T10:15:00Z",
         description: "Revoked suspicious OAuth app grants and forced re-consent for affected tenants.",
         category: "Containment",
       },
     ],
     nodes: [
       {
         id: "attacker-7",
         type: "customNode",
         position: { x: 50, y: 200 },
         data: {
           label: "Attacker Infrastructure",
           type: "attacker",
           criticality: "Critical",
           services: ["C2 Server", "OAuth Token Server"],
           actions: [
             {
               id: "action-1",
               type: "Initial Access",
               technique: "OAuth Token Theft",
               details: "Stole OAuth tokens from compromised applications",
             },
           ],
           description: "External attacker with stolen OAuth tokens",
           displaySettings: { ...defaultDisplaySettings },
           isCompromised: false,
    investigationStatus: "No Status",
         },
       },
                {
           id: "entra-id-tenant",
           type: "customNode",
           position: { x: 300, y: 100 },
           data: {
             label: "Entra ID Tenant",
             type: "cloud-tenant",
             criticality: "Critical",
           services: ["OAuth 2.0", "SAML", "SCIM", "Graph API"],
           actions: [
             {
               id: "action-2",
               type: "Initial Access",
               technique: "OAuth Token Abuse",
               details: "Used stolen OAuth token to access Entra ID",
             },
           ],
           description: "Microsoft Entra ID (Azure AD) tenant",
           displaySettings: { ...defaultDisplaySettings },
                       cloudTenantData: {
              tenantId: "12345678-1234-1234-1234-123456789012",
              tenantName: "company.onmicrosoft.com",
              cloudProvider: "Azure",
              tenantType: "Entra ID",
              subscriptionId: "87654321-4321-4321-4321-210987654321",
              region: "eastus",
              environment: "Production",
              resourceCount: 500,
              securityScore: 88,
            },
           isCompromised: true,
    investigationStatus: "No Status",
         },
       },
                {
           id: "aws-organizations",
           type: "customNode",
           position: { x: 600, y: 100 },
           data: {
             label: "AWS Organizations",
             type: "cloud-tenant",
             criticality: "Critical",
           services: ["Organizations API", "IAM", "SSO"],
           actions: [
             {
               id: "action-3",
               type: "Lateral Movement",
               technique: "Cross-Account Access",
               details: "Used compromised admin role to access organization",
             },
           ],
           description: "AWS Organizations for multi-account management",
           displaySettings: { ...defaultDisplaySettings },
                       cloudTenantData: {
              tenantId: "123456789012",
              tenantName: "company-aws-org",
              cloudProvider: "AWS",
              tenantType: "AWS Organizations",
              accountId: "123456789012",
              region: "us-east-1",
              environment: "Production",
              resourceCount: 1200,
              securityScore: 92,
            },
           isCompromised: true,
    investigationStatus: "No Status",
         },
       },
                {
           id: "google-workspace",
           type: "customNode",
           position: { x: 900, y: 100 },
           data: {
             label: "Google Workspace",
             type: "cloud-tenant",
             criticality: "Critical",
           services: ["Admin SDK", "Gmail API", "Drive API"],
           actions: [
             {
               id: "action-4",
               type: "Lateral Movement",
               technique: "API Abuse",
               details: "Abused Google Workspace APIs for data access",
             },
           ],
           description: "Google Workspace tenant for collaboration",
           displaySettings: { ...defaultDisplaySettings },
                       cloudTenantData: {
              tenantId: "C123456789",
              tenantName: "company.com",
              cloudProvider: "GCP",
              tenantType: "Google Workspace",
              projectId: "company-workspace-123456",
              region: "us-central1",
              environment: "Production",
              resourceCount: 300,
              securityScore: 85,
            },
           isCompromised: true,
    investigationStatus: "No Status",
         },
       },
                {
           id: "okta-tenant",
           type: "customNode",
           position: { x: 300, y: 300 },
           data: {
             label: "Okta Identity Provider",
             type: "cloud-tenant",
             criticality: "Critical",
           services: ["OAuth 2.0", "SAML", "SCIM", "Admin API"],
           actions: [
             {
               id: "action-5",
               type: "Lateral Movement",
               technique: "Identity Provider Compromise",
               details: "Compromised Okta admin account",
             },
           ],
           description: "Okta identity and access management platform",
           displaySettings: { ...defaultDisplaySettings },
                       cloudTenantData: {
              tenantId: "00abc123def456",
              tenantName: "company.okta.com",
              cloudProvider: "Other",
              tenantType: "Okta",
              region: "us-east-1",
              environment: "Production",
              resourceCount: 150,
              securityScore: 90,
            },
           isCompromised: true,
    investigationStatus: "No Status",
         },
       },
                {
           id: "auth0-tenant",
           type: "customNode",
           position: { x: 600, y: 300 },
           data: {
             label: "Auth0 Tenant",
             type: "cloud-tenant",
             criticality: "High",
           services: ["OAuth 2.0", "OpenID Connect", "Management API"],
           actions: [
             {
               id: "action-6",
               type: "Lateral Movement",
               technique: "API Key Abuse",
               details: "Used stolen API keys to access Auth0 management API",
             },
           ],
           description: "Auth0 identity as a service platform",
           displaySettings: { ...defaultDisplaySettings },
                       cloudTenantData: {
              tenantId: "auth0|company",
              tenantName: "company.auth0.com",
              cloudProvider: "Other",
              tenantType: "Auth0",
              region: "us-east-1",
              environment: "Production",
              resourceCount: 75,
              securityScore: 87,
            },
           isCompromised: true,
    investigationStatus: "No Status",
         },
       },
       {
         id: "exfiltration-5",
         type: "customNode",
         position: { x: 900, y: 300 },
         data: {
           label: "Data Exfiltration",
           type: "exfiltration",
           hostname: "exfil-server.com",
           ipAddress: "192.168.100.100",
           os: "Linux",
           criticality: "Critical",
           services: ["HTTP", "HTTPS", "FTP"],
           actions: [
             {
               id: "action-7",
               type: "Exfiltration",
               technique: "Data Transfer Size Limits",
               details: "Exfiltrated user data from multiple tenants",
             },
           ],
           description: "External server for data exfiltration",
           displaySettings: { ...defaultDisplaySettings },
           exfiltrationData: {
             method: "Cloud Storage",
             destination: "s3://attacker-bucket/user-data",
             protocol: "HTTPS",
             encryption: true,
             compression: true,
             dataTypes: ["User Credentials", "OAuth Tokens", "API Keys"],
             volumeGB: 50,
             transferRate: "10 MB/s",
             detectionEvasion: ["Traffic Mimicry", "Legitimate Service Abuse"],
             exfiltrationWindow: "Off-peak",
             status: "Completed",
           },
           isCompromised: false,
    investigationStatus: "No Status",
         },
       },
     ],
     edges: [
       {
         id: "e-attacker-entra",
         source: "attacker-7",
         target: "entra-id-tenant",
         type: "customEdge",
         data: {
           label: "OAuth Token Abuse",
           actionType: "Initial Access",
           toolUsed: "Stolen OAuth Token",
           userUsed: "anonymous",
           timestamp: "2024-01-15T10:00:00Z",
           mitreAttackId: "T1078.004",
           description: "Used stolen OAuth token to access Entra ID tenant",
         },
       },
       {
         id: "e-entra-aws",
         source: "entra-id-tenant",
         target: "aws-organizations",
         type: "customEdge",
         data: {
           label: "Cross-Cloud Access",
           actionType: "Lateral Movement",
           toolUsed: "AWS CLI",
           userUsed: "entra-sync-user",
           timestamp: "2024-01-15T10:15:00Z",
           mitreAttackId: "T1078.004",
           description: "Used Entra ID credentials to access AWS Organizations",
         },
       },
       {
         id: "e-aws-google",
         source: "aws-organizations",
         target: "google-workspace",
         type: "customEdge",
         data: {
           label: "API Abuse",
           actionType: "Lateral Movement",
           toolUsed: "Google Admin SDK",
           userUsed: "aws-sync-service",
           timestamp: "2024-01-15T10:30:00Z",
           mitreAttackId: "T1078.004",
           description: "Used AWS credentials to access Google Workspace APIs",
         },
       },
       {
         id: "e-attacker-okta",
         source: "attacker-7",
         target: "okta-tenant",
         type: "customEdge",
         data: {
           label: "Admin Compromise",
           actionType: "Initial Access",
           toolUsed: "Okta Admin Console",
           userUsed: "admin@company.com",
           timestamp: "2024-01-15T11:00:00Z",
           mitreAttackId: "T1078.004",
           description: "Compromised Okta admin account through phishing",
         },
       },
       {
         id: "e-okta-auth0",
         source: "okta-tenant",
         target: "auth0-tenant",
         type: "customEdge",
         data: {
           label: "API Key Theft",
           actionType: "Lateral Movement",
           toolUsed: "Auth0 Management API",
           userUsed: "okta-sync-user",
           timestamp: "2024-01-15T11:15:00Z",
           mitreAttackId: "T1078.004",
           description: "Used Okta credentials to steal Auth0 API keys",
         },
       },
       {
         id: "e-entra-exfiltration",
         source: "entra-id-tenant",
         target: "exfiltration-5",
         type: "customEdge",
         data: {
           label: "User Data Exfiltration",
           actionType: "Exfiltration",
           toolUsed: "Graph API",
           userUsed: "entra-admin",
           timestamp: "2024-01-15T12:00:00Z",
           mitreAttackId: "T1041",
           description: "Exfiltrated user data from Entra ID tenant",
         },
       },
       {
         id: "e-aws-exfiltration",
         source: "aws-organizations",
         target: "exfiltration-5",
         type: "customEdge",
         data: {
           label: "Account Data Exfiltration",
           actionType: "Exfiltration",
           toolUsed: "AWS Organizations API",
           userUsed: "aws-admin",
           timestamp: "2024-01-15T12:15:00Z",
           mitreAttackId: "T1041",
           description: "Exfiltrated account data from AWS Organizations",
         },
       },
       {
         id: "e-google-exfiltration",
         source: "google-workspace",
         target: "exfiltration-5",
         type: "customEdge",
         data: {
           label: "Workspace Data Exfiltration",
           actionType: "Exfiltration",
           toolUsed: "Google Admin SDK",
           userUsed: "google-admin",
           timestamp: "2024-01-15T12:30:00Z",
           mitreAttackId: "T1041",
           description: "Exfiltrated workspace data from Google Workspace",
         },
       },
       {
         id: "e-okta-exfiltration",
         source: "okta-tenant",
         target: "exfiltration-5",
         type: "customEdge",
         data: {
           label: "Identity Data Exfiltration",
           actionType: "Exfiltration",
           toolUsed: "Okta Admin API",
           userUsed: "okta-admin",
           timestamp: "2024-01-15T12:45:00Z",
           mitreAttackId: "T1041",
           description: "Exfiltrated identity data from Okta tenant",
         },
       },
       {
         id: "e-auth0-exfiltration",
         source: "auth0-tenant",
         target: "exfiltration-5",
         type: "customEdge",
         data: {
           label: "Auth Data Exfiltration",
           actionType: "Exfiltration",
           toolUsed: "Auth0 Management API",
           userUsed: "auth0-admin",
           timestamp: "2024-01-15T13:00:00Z",
           mitreAttackId: "T1041",
           description: "Exfiltrated authentication data from Auth0 tenant",
         },
       },
     ],
   },
 ] 
